### ISSUE TITLE
[Bug]: The mouse controller | Games | mouse controller to move mouse is not functioning properly 

### ISSUE THREAD

**Issue by SimranCarvalho** [thinkonmay/thinkremote-v2#13]
### What happened?

Description: If we try to move the mouse with the help of the mouse controller the mouse is moving too fast & the controller is moving all over the place causing difficulty to use it properly 

Actual Behaviour: The mouse controller should freeze in one place and only the controller should move 
Expected Behaviour: The mouse is moving too fast & moving all over the place

https://user-images.githubusercontent.com/126673284/224303218-c2164d9c-68ae-4b83-b3ad-8f15d52bbb17.mp4

### To reproduce the behavior?

Steps:

1. Enable the mouse controller 
2. And move the mouse forward & backward 

### Which device / platform are you seeing the problem on?

Android

### What browser are you seeing the problem on?

Chrome

**Comment by carosaome** [comment]
Your first click to the mouse icon enables to show and change the mouse's position. Click one more time to fix the postion.

**Comment by pigeatgarlic** [comment]
I would say @SimranCarvalho is misunderstood our intention of gamepad feature, so I can sort this is not a bug
